before_script:
  - pip3 install -r requirements.txt

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive


tests:
  stage: test
  script:
    - python3 ./manage.py test --settings=PiLock.settings.debug
  tags:
    - django