# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEBUG', 'Debug Mode'), ('UPDATE', 'Update available'), ('SEC', 'Security Issue')], default='DEBUG', max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
