# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
