# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameEntered', models.CharField(max_length=150)),
                ('is_unlock_attempt', models.BooleanField(default=False)),
                ('successful', models.BooleanField(default=False)),
                ('ip', models.CharField(default='0.0.0.0', max_length=15)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
