# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accessattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='usernameEntered',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
