# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170906_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='authToken',
            field=models.CharField(max_length=64),
        ),
    ]
