# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170906_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
