# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170907_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wearToken',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
