# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_weartoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='authToken',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wearToken',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
